# Generated by Django 4.1.5 on 2023-07-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='blogapp2.tag'),
        ),
    ]
