# Generated by Django 4.1.5 on 2023-01-19 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0003_alter_news_options_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='new',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newsapp.news'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
