# Generated by Django 4.1.5 on 2023-01-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_news_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['tag', 'published_at'], 'permissions': {('can_publish', 'Может публиковать')}, 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
