# Generated by Django 4.1.5 on 2023-02-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_sale_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('products', models.ManyToManyField(related_name='shops', to='shopapp.product')),
            ],
        ),
    ]
