# Generated by Django 4.1.5 on 2023-01-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verificied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='news',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
