# Generated by Django 4.1.5 on 2023-01-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_profile_is_verificied_profile_news_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': {('can_verify', 'Может верифицировать')}},
        ),
    ]
